# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 */3 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cancel:
    name: auto-cancellation-running-action
    runs-on: ubuntu-latest
    steps:
      - uses: fauguste/auto-cancellation-running-action@0.1.4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    timeout-minutes: 1380

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set Variables
        uses: allenevans/set-env@v2.0.0
        with:
          EVPN_ACT_CODE: ${{ secrets.EVPN_ACT_CODE}}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          email_670: ${{ secrets.email_670 }} #Lucknow
          email_240: ${{ secrets.email_240 }} #Ranchi
          email_725: ${{ secrets.email_725 }} #Kolkata
          email_650: ${{ secrets.email_650 }} #GautamBudh Nagar

      - name: Install Express VPN
        run: |
          sudo wget https://www.expressvpn.works/clients/linux/expressvpn_3.7.0.29-1_amd64.deb
          sudo dpkg -i expressvpn_3.7.0.29-1_amd64.deb

      - name: Start Express VPN
        run: |
          sudo apt-get install expect
          /usr/bin/expect <<EOD
          spawn expressvpn activate 
          expect "Enter activation code: "
          send "$EVPN_ACT_CODE\r"
          expect "Activated"
          EOD
          expressvpn connect "India - Mumbai - 1"
          expressvpn status

      - name: Confirm IP location
        run: |
          curl ipinfo.io

      - name: Find all available slots for vaccination
        run: bash check_vaccine.sh